### ISSUE TITLE
http server support?

### ISSUE THREAD

**Issue by lubia** [mailgun/godebug#24]
Hello,

I'm trying debug code like this:
```
package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {
	_ = "breakpoint"
	var count int
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) { fmt.Fprintf(w, "Hello, world") })
	go log.Fatal(http.ListenAndServe(":8080", nil))
	fmt.Println(count)
}
```

but it stop at line

```
go log.Fatal(http.ListenAndServe(":8080", nil))
```
![image](https://cloud.githubusercontent.com/assets/2741940/7582492/afee4720-f8c0-11e4-931f-398ddbd8b9f6.png)

any one help me?

**Comment by nuss-justin** [comment]
The bug is in your code. Calling `go log.Fatal(http.ListenAndServe(":8080", nil))` is the same as:

```go
err := http.ListenAndServe(":8080", nil) // blocks the goroutine
go log.Fatal(err)
```

You are only calling log.Fatal in another goroutine. The evaluation of the arguments (in this case your http.ListenAndServe call) still happens in the calling goroutine, which in your case is the main goroutine. This blocks your main goroutine including the debugger.

You can fix your code with an anonymous function:

```go
go func() {
    log.Fatal(http.ListenAndServe(":8080", nil))
}()
```

**Comment by lubia** [comment]
thanks,solved
 @nuss-justin
