### ISSUE TITLE
instrumentation error "cannot use _ as value"

### ISSUE THREAD

**Issue by kylehr** [mailgun/godebug#42]
Hi guys,

Awesome piece of work BTW.  Are you thinking about a code coverage extension at all :)

When instrumenting github.com/ugorji/go/codec I get some lines that look like:
- /var/folders/rh/l35fk0qd6gn4nc0czl94q37r0000gn/T/godebug838019398/src/github.com/ugorji/go/codec/fast-path.generated.go:4755: cannot use _ as value

followed by:

- too many errors

and the program gives up.

Is there some way around this without changing the third party code?  Is there a way to skip one file in a package?  

Thanks for any help.

Regards,
Kyle

**Comment by jeremyschlatter** [comment]
Hi @kylehr,

Thanks for the bug report! The "cannot use _ as value" problem is now fixed. I even found a second issue with godebug when I was testing github.com/ugorji/go/codec -- that issue is fixed now, too.

> Awesome piece of work BTW. Are you thinking about a code coverage extension at all :)

Glad you like it :) For code coverage, did you know about this? https://blog.golang.org/cover

-Jeremy
